# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculadora
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  rules:
    - host: www.calculadora-express.com
      http:
        paths:
          - path: /calcular
            pathType: Prefix
            backend:
              service:
                name: calculadora
                port:
                  number: 3000
